steps = [{'code': 'Animation', 'type': 'Step', 'id': 5, 'entity_type': 'Shot'},
		{'code': 'Lighting', 'type': 'Step', 'id': 7, 'entity_type': 'Shot'},
		{'code': 'Compositing', 'type': 'Step', 'id': 8, 'entity_type': 'Shot'},
		{'code': 'Art', 'type': 'Step', 'id': 9, 'entity_type': 'Asset'},
		{'code': 'Model', 'type': 'Step', 'id': 10, 'entity_type': 'Asset'},
		{'code': 'Rig', 'type': 'Step', 'id': 11, 'entity_type': 'Asset'},
		{'code': 'Surface', 'type': 'Step', 'id': 12, 'entity_type': 'Asset'},
		{'code': 'Layout', 'type': 'Step', 'id': 13, 'entity_type': 'Shot'},
		{'code': 'Layout', 'type': 'Step', 'id': 17, 'entity_type': 'Sequence'},
		{'code': 'Render', 'type': 'Step', 'id': 43, 'entity_type': 'Shot'},
		{'code': 'texture', 'type': 'Step', 'id': 49, 'entity_type': 'Asset'},
		{'code': 'TechAnim', 'type': 'Step', 'id': 54, 'entity_type': 'Shot'},
		{'code': 'FX', 'type': 'Step', 'id': 55, 'entity_type': 'Shot'},
		{'code': 'SetDress', 'type': 'Step', 'id': 57, 'entity_type': 'Asset'},
		{'code': 'General', 'type': 'Step', 'id': 59, 'entity_type': 'Asset'},
		{'code': '2D', 'type': 'Step', 'id': 60, 'entity_type': 'Shot'},
		{'code': 'Hero', 'type': 'Step', 'id': 70, 'entity_type': 'Asset'}]
